### ISSUE TITLE
Header Bild anpassen (Mejri & Jakupi)

### ISSUE THREAD

**Issue by finnge** [th-koeln/mi-bachelor-screendesign-projekte#44]
Hi @dalilame,

ihr habt in eurem Teaser-Bild die Überschrift eingefügt. Ihr habt die Möglichkeit in einem neuen Pull-Request das Bild anzupassen und auszutauschen.

Falls nicht könnt ihr gerne Kommentieren und dieses Issue schließen.

![image](https://user-images.githubusercontent.com/19761338/112537595-29804f00-8daf-11eb-885e-792ae82e1839.jpeg)

**Comment by dalilame** [comment]
Hi, wir haben es geändert und neu hochgeladen.

**Comment by finnge** [comment]
Hi,

ihr habt noch keinen neuen Pull-Request gestellt

**Comment by dalilame** [comment]
Hey, ist es jetzt richtig?

**Comment by finnge** [comment]
Hey sorry. Für die späte Antwort. Leider müsst ihr dieses Repo erneut forken und dort eure Änderungen vornehmen.

**Comment by finnge** [comment]
close issue
